export const onlineUsers: string='UserOnline'
export const socketId: string='socketId'
export const searchUser: string='searchUser'
export const searchedUser: string='searchedUser'
export const noToken: string='noToken'
export const invalidToken: string='invalidToken'
export const userNotFound: string='userNotFound'
export const emptySearchBar: string='emptySearchBar'
export const sendConfession: string='send-confession'
export const recieveConfession: string='recieve-sonfession'
export const updateFirebaseConfession: string='update-Firebase-Confession';
export const tokenLost: string='token-lost';
export const recieveAllMessages: string='recieve-all-messages';
export const appIsClosed: string='app-is-closed';
export const updateConfssionStatus: string='update-status'
export const createChat:string='create-chat'
export const readConfession:string='read-confession'