version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    user: "node:node"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
      - redis-testing
      - rabbitmq-testing
  redis:
    image: redis
    ports:
      - "6381:6379"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5674:5762"
      - "15674:15672"
  redis-testing:
    image: redis
    ports:
      - "6380:6300"
  rabbitmq-testing:
    image: rabbitmq
    ports:
      - "5673:5673"
      - "15673:15673"
  