syntax = "proto3";

option go_package = "github.com/Manik2708/pkg/grpc";

package grpc;

service QueueService{
    rpc GetMessages(GetMessagesRequest) returns (stream GetMessagesResponse){}
    rpc SaveMessage(SaveMessageRequest) returns (SaveMessageResponse){}
    rpc DeleteMessagesById(GetMessagesRequest) returns (SaveMessageResponse){}
}

message GetMessagesRequest{
    string id = 1;
}

message GetMessagesResponse{
    string id = 1;
    bytes content = 2;
}

message SaveMessageRequest{
    string id = 1;
    bytes content = 2;
}

message SaveMessageResponse{
    bool success = 1; 
}