apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
data:
  cookie: PUT_YOUR_COOKIE_HERE
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
data:
  user: PUT_THE_USERNAME_HERE
  pass: PUT_THE_PASSWORD_HERE