apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
  namespace: hi-rabbitmq
data:
  .erlang.cookie: UE5JUkRNSFVBV0tDT1hPU1dEU1A=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
  namespace: hi-rabbitmq
data:
  user: bWFuaWsyNzA4
  pass: RG1hbmlrYUAyNzI3