apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
  namespace: hi-rabbitmq
data:
  .erlang.cookie: PUT_YOUR_ERLANG_COOKIE_HERE
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
  namespace: hi-rabbitmq
data:
  user: ENTER_USER_NAME
  pass: ENTER_PASSWORD