name: Build Application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Build Enviornment
        run: docker compose up -d --no-color --wait
        working-directory: scripts
      - name: Install dependencies
        run: npm install
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v2
        with:
          time: 10s
      - name: Create .env file
        run: touch .env
      - name: Edit file for running on docker
        run: echo "RUNNING_ON_DOCKER=true" >> .env 
      - name: Build server
        run: npm run build
      - name: Remove Build Enviornment
      - run: docker compose down  
      
      
