name: Test Application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v2
        with:
          time: 10s
      - name: Check formatting
        run: npm run format:check 
      - name: Check Circular Dependencies
        run: npx madge --circular --extensions ts ./
      
      
