name: Test Application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Testing Enviornment
        run: |
          chmod +x docker_compose_up.sh
          ./docker_compose_up.sh
        working-directory: scripts
      - name: Install dependencies
        run: npm install
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v2
        with:
          time: 10s
      - name: Run tests
        run: npm run test:e2e
      - name: Remove Testing Enviornment
      - run: |
          chmod +x docker_compose_down.sh
          ./docker_compose_down.sh   
      
      
